load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["line_on_line_intersection.go"],
    visibility = ["//visibility:public"],
    deps = ["//:go_default_library"],
)
